import { Suspense } from "react";
import Login from "./_components/login";

export const metadata = {
  title: "Account | BOOOKS",
  description: "Generated by create next app",
};

export default function LoginPage() {
  return (
    <Suspense>
      <Login />
    </Suspense>
  );
}
